export const SYNC_MAP = '@@map/sync'
export const UPDATE_MAP = '@@map/updateMap'
export const SYNC_CANCEL_MAP = '@@map/syncCancelled'
export const SYNC_FAILED_MAP = '@@map/syncFailed'
export const UPDATE_DATA_LOADING_TIME = '@@data/updateDataLoadingTime'
export const SET_START_RENDERING_TIME = '@@data/setStartRenderingTime'
